# Generated by Django 6.0.6 on 2026-06-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='academy/pdfs/'),
        ),
        migrations.AddField(
            model_name='module',
            name='target_roles',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('company', 'Entreprise'), ('both', 'Tous')], default='citizen', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', null=True),
        ),
    ]
