# Generated by Django 6.0.6 on 2026-06-17 01:09

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_module_pdf_file_module_target_roles_module_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, help_text='Fichier vidéo (mp4, webm, mov, avi)', null=True, upload_to='academy/videos/', validators=[academy.models.validate_video_file]),
        ),
    ]
