# Generated by Django 6.0.6 on 2026-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_module_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Image illustrative pour la question (optionnelle)', null=True, upload_to='academy/questions/'),
        ),
    ]
