# Generated by Django 6.0.6 on 2026-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de couverture du module (vignette)', null=True, upload_to='academy/modules/'),
        ),
    ]
