services:

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    container_name: cybersafe-auth
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth/.env
    volumes:
      - ./services/auth:/app
      - auth_data:/app/data

  chatbot:
    build:
      context: ./services/chatbot
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/chatbot:/app

  alerts:
    build:
      context: ./services/alerts
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/alerts:/app

volumes:
  auth_data:
